# Generated by Django 6.0 on 2026-01-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='deleated_at',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='activity',
            name='deleted_at',
            field=models.BooleanField(null=True),
        ),
    ]
