# Generated by Django 5.2.8 on 2025-12-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_is_deleted_organization_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
