# Generated by Django 6.0 on 2026-02-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_membership_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')])),
                ('price', models.IntegerField(choices=[(500, 500), (1000, 1000), (5000, 5000)])),
                ('rate_limit', models.CharField(choices=[('10/hour', '10/hour'), ('15/hour', '15/hour'), ('20/hour', '20/hour')])),
                ('duration', models.IntegerField(choices=[(30, 30), (60, 60), (365, 365)])),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('txnid', models.CharField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
    ]
