# Generated by Django 6.0 on 2026-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_subscription_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='rate_limit',
            field=models.CharField(choices=[('200/hour', '200/hour'), ('500/hour', '500/hour'), ('1000/hour', '1000/hour')]),
        ),
    ]
