# Generated by Django 6.0 on 2026-01-20 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('workspace', '0003_rename_deleated_at_workspace_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
    ]
