# Generated by Django 6.0 on 2026-01-21 09:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='aa', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
