# Generated by Django 6.0 on 2026-03-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_slug'),
        ('workspace', '0003_rename_deleated_at_workspace_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
    ]
